### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by vivekkj123** [rbuckton/prex#7]
Hi there,
Please tag the new npm version (i.e. 0.4.7) of this module in this upstream repo.. we want to pack this awesome npm module to debian, so please do as soon as possible,

Regards,
VIVEK K J
www.vivekkj.me
Debian Community

**Comment by rbuckton** [comment]
The `prex` package is essentially deprecated, as I've moved all of the functionality to [`@esfx/async`](https://esfx.js.org/#async) ([GitHub](https://github.com/esfx/esfx)), which is essentially a collection of the following packages:

Existing APIs:
- `CancelError`, `CancellationTokenRegistration` -> [`@esfx/cancelable`](https://esfx.js.org/esfx/api/cancelable.html) (NOTE: some API surface changes here)
- `CancellationToken`, `CancellationTokenSource` -> [`@esfx/async-canceltoken`](https://esfx.js.org/esfx/api/async-canceltoken.html) (NOTE: some API surface changes here)
- `ManualResetEvent` -> [`@esfx/async-manualresetevent`](https://esfx.js.org/esfx/api/async-manualresetevent.html)
- `AutoResetEvent` -> [`@esfx/async-autoresetevent`](https://esfx.js.org/esfx/api/async-autoresetevent.html)
- `Semaphore` -> [`@esfx/async-semaphore`](https://esfx.js.org/esfx/api/async-semaphore.html)
- `CountdownEvent` -> [`@esfx/async-countdown`](https://esfx.js.org/esfx/api/async-countdown.html)
- `Barrier` -> [`@esfx/async-barrier`](https://esfx.js.org/esfx/api/async-barrier.html)
- `ReaderWriterLock` -> [`@esfx/async-readerwriterlock`](https://esfx.js.org/esfx/api/async-readerwriterlock.html)
- `Deferred` -> [`@esfx/async-deferred`](https://esfx.js.org/esfx/api/async-deferred.html)
- `AsyncQueue` ->[`@esfx/async-queue`](https://esfx.js.org/esfx/api/async-queue.html)
- `AsyncStack` -> [`@esfx/async-stack`](https://esfx.js.org/esfx/api/async-stack.html)
- `delay` -> [`@esfx/async-delay`](https://esfx.js.org/esfx/api/async-delay.html)

New Async Coordination APIs:
- [`@esfx/async-mutex`](https://esfx.js.org/esfx/api/async-mutex.html)
- [`@esfx/async-conditionvariable`](https://esfx.js.org/esfx/api/async-conditionvariable.html)
- [`@esfx/async-lazy`](https://esfx.js.org/esfx/api/async-lazy.html)

DOM Interop APIs:
- [`@esfx/cancelable-dom`](https://esfx.js.org/esfx/api/cancelable-dom.html) provides `toAbortSignal`
- [`@esfx/cancelable-dom-shim`](https://esfx.js.org/esfx/api/cancelable-dom-shim.html) which adds `@esfx/cancelable` core API support to `AbortController`/`AbortSignal`

The `@esfx/cancelable` package is based on https://github.com/tc39/proposal-cancellation/issues/22.

As far as the differences between cancellation primitives:

## Creating a "source" for cancellation
```ts
// prex
import { CancellationTokenSource } from "prex";
const source = new CancellationTokenSource();
source.token; // gets the token
source.cancel(); // cancels the source

// @esfx/async-canceltoken
import { CancelToken } from "@esfx/async-canceltoken";
const source = CancelToken.source();
source.token; // gets the token
source.cancel(); // cancels the source
```

## Creating a "token" linked to multiple tokens
```ts
// prex
import { CancellationTokenSource } from "prex";
const outer = new CancellationTokenSource();
const inner1 = new CancellationTokenSource([outer]);
const inner2 = new CancellationTokenSource([outer]);
const token1 = inner1.token; // token canceled when either outer or inner1 are canceled
const token2 = inner2.token; // token canceled when either outer or inner2 are canceled
inner1.cancel(); // cancels 'token1'
outer.cancel(); // cancels 'token1' and 'token2'

// @esfx/async-canceltoken
import { CancelToken } from "prex";
const outer = CancelToken.source();
const inner1 = CancelToken.source();
const inner2 = CancelToken.source();
const token1 = CancelToken.race([outer, inner1]); // token canceled when either outer or inner1 are canceled
const token2 = CancelToken.race([outer, inner2]); // token canceled when either outer or inner2 are canceled
inner1.cancel(); // cancels 'token1'
outer.cancel(); // cancels 'token1' and 'token2'
```

## Subscribing to a "token"
```ts
// prex
import { CancellationTokenSource } from "prex";
const source = new CancellationTokenSource();
const token = source.token;
const registration = token.register(() => { /* called when canceled */ });
registration.unregister(); // stop listening for cancelation

// @esfx/async-canceltoken
import { CancelToken } from "@esfx/async-canceltoken";
const source = CancelToken.source();
const token = source.token;
const subscription = token.subscribe(() => { /* called when canceled */ });
subscription.unsubscribe(); // stop listening for cancellation

// alternatively, subscriptions also support the @esfx/disposable core API
// based on https://github.com/tc39/proposal-explicit-resource-management
import { Disposable } from "@esfx/disposable";
subscription[Disposable.dispose]();
```

**Comment by vivekkj123** [comment]
But while running the gulp test on esfx pacakge, it shows prex as a dependency, that is why I said you to tag new version in this package...

**Comment by pravi** [comment]
@rbuckton can you remove the build dependency on prex from esfx?

**Comment by rbuckton** [comment]
I've removed prex as a devDependency, and will be pushing an update to esfx with the change shortly.
